name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Install dependencies
      run: msbuild /t:Restore /p:Configuration=Release Macropse/macropse.sln
    - name: Build
      run: msbuild /p:Configuration=Release IO/IO.csproj && msbuild /p:Configuration=Release Macropse/macropse.csproj
